//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_UVM_Control_Presupuestario
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOLETA
    {
        public int ID { get; set; }
        public long NUMERO_BOLETA { get; set; }
        public System.DateTime FECHA_BOLETA { get; set; }
        public long MONTO { get; set; }
        public string DETALLE { get; set; }
        public int OPEXID { get; set; }
        public int CAPEXID { get; set; }
    
        public virtual OPEX OPEX { get; set; }
        public virtual CAPEX CAPEX { get; set; }
    }
}
