
-- --------------------------------------------------
-- Entity Designer DDL Script for SQL Server 2005, 2008, 2012 and Azure
-- --------------------------------------------------
-- Date Created: 01/24/2023 17:27:04
-- Generated from EDMX file: C:\Users\jesus\source\repos\Sistema_UVM_Control_Presupuestario\Model1.edmx
-- --------------------------------------------------

SET QUOTED_IDENTIFIER OFF;
GO
USE [SCP_UVM];
GO
IF SCHEMA_ID(N'dbo') IS NULL EXECUTE(N'CREATE SCHEMA [dbo]');
GO

-- --------------------------------------------------
-- Dropping existing FOREIGN KEY constraints
-- --------------------------------------------------

IF OBJECT_ID(N'[dbo].[FK_USUARIOROL]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[USUARIOs] DROP CONSTRAINT [FK_USUARIOROL];
GO
IF OBJECT_ID(N'[dbo].[FK_PERSONA_JURIDICARENDICION]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[RENDICIONes] DROP CONSTRAINT [FK_PERSONA_JURIDICARENDICION];
GO
IF OBJECT_ID(N'[dbo].[FK_PERSONA_JURIDICACAPEX]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[CAPEXes] DROP CONSTRAINT [FK_PERSONA_JURIDICACAPEX];
GO
IF OBJECT_ID(N'[dbo].[FK_PERSONA_NATURALOPEX]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[OPEXes] DROP CONSTRAINT [FK_PERSONA_NATURALOPEX];
GO
IF OBJECT_ID(N'[dbo].[FK_PERSONA_NATURALPROP_DIPLOMADO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[PROP_DIPLOMADOs] DROP CONSTRAINT [FK_PERSONA_NATURALPROP_DIPLOMADO];
GO
IF OBJECT_ID(N'[dbo].[FK_PERSONA_NATURALPAGO_DIPLOMADO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[PAGO_DIPLOMADOs] DROP CONSTRAINT [FK_PERSONA_NATURALPAGO_DIPLOMADO];
GO
IF OBJECT_ID(N'[dbo].[FK_PERSONA_NATURALREEMBOLSO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[REEMBOLSOs] DROP CONSTRAINT [FK_PERSONA_NATURALREEMBOLSO];
GO
IF OBJECT_ID(N'[dbo].[FK_PERSONA_NATURALRENDICION]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[RENDICIONes] DROP CONSTRAINT [FK_PERSONA_NATURALRENDICION];
GO
IF OBJECT_ID(N'[dbo].[FK_OPEXFACTURA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[FACTURAs] DROP CONSTRAINT [FK_OPEXFACTURA];
GO
IF OBJECT_ID(N'[dbo].[FK_OPEXBOLETA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[BOLETAs] DROP CONSTRAINT [FK_OPEXBOLETA];
GO
IF OBJECT_ID(N'[dbo].[FK_CAPEXBOLETA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[BOLETAs] DROP CONSTRAINT [FK_CAPEXBOLETA];
GO
IF OBJECT_ID(N'[dbo].[FK_CAPEXFACTURA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[FACTURAs] DROP CONSTRAINT [FK_CAPEXFACTURA];
GO
IF OBJECT_ID(N'[dbo].[FK_CONSOLIDADOCARRERA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[PROGRAMAs_CARRERA] DROP CONSTRAINT [FK_CONSOLIDADOCARRERA];
GO
IF OBJECT_ID(N'[dbo].[FK_CONSOLIDADODIPLOMADO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[PROGRAMAs_DIPLOMADO] DROP CONSTRAINT [FK_CONSOLIDADODIPLOMADO];
GO
IF OBJECT_ID(N'[dbo].[FK_CONSOLIDADOMAGISTER]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[PROGRAMAs_MAGISTER] DROP CONSTRAINT [FK_CONSOLIDADOMAGISTER];
GO
IF OBJECT_ID(N'[dbo].[FK_CONSOLIDADOMES]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[MESes] DROP CONSTRAINT [FK_CONSOLIDADOMES];
GO
IF OBJECT_ID(N'[dbo].[FK_SALIDA_TERRENOMES_SALIDA_TERRENO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[SALIDA_TERRENOMES] DROP CONSTRAINT [FK_SALIDA_TERRENOMES_SALIDA_TERRENO];
GO
IF OBJECT_ID(N'[dbo].[FK_SALIDA_TERRENOMES_MES]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[SALIDA_TERRENOMES] DROP CONSTRAINT [FK_SALIDA_TERRENOMES_MES];
GO
IF OBJECT_ID(N'[dbo].[FK_PERSONA_JURIDICASOLICITUD]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[SOLICITUDes] DROP CONSTRAINT [FK_PERSONA_JURIDICASOLICITUD];
GO
IF OBJECT_ID(N'[dbo].[FK_SOLICITUDCAPEX]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[SOLICITUDes] DROP CONSTRAINT [FK_SOLICITUDCAPEX];
GO
IF OBJECT_ID(N'[dbo].[FK_SOLICITUDOPEX]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[SOLICITUDes] DROP CONSTRAINT [FK_SOLICITUDOPEX];
GO
IF OBJECT_ID(N'[dbo].[FK_PERSONA_NATURALSOLICITUD_PERSONA_NATURAL]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[PERSONA_NATURALSOLICITUD] DROP CONSTRAINT [FK_PERSONA_NATURALSOLICITUD_PERSONA_NATURAL];
GO
IF OBJECT_ID(N'[dbo].[FK_PERSONA_NATURALSOLICITUD_SOLICITUD]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[PERSONA_NATURALSOLICITUD] DROP CONSTRAINT [FK_PERSONA_NATURALSOLICITUD_SOLICITUD];
GO
IF OBJECT_ID(N'[dbo].[FK_CAMBIOOPEX_CAMBIO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[CAMBIOOPEX] DROP CONSTRAINT [FK_CAMBIOOPEX_CAMBIO];
GO
IF OBJECT_ID(N'[dbo].[FK_CAMBIOOPEX_OPEX]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[CAMBIOOPEX] DROP CONSTRAINT [FK_CAMBIOOPEX_OPEX];
GO
IF OBJECT_ID(N'[dbo].[FK_MAGISTEROPEX_MAGISTER]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[MAGISTEROPEX] DROP CONSTRAINT [FK_MAGISTEROPEX_MAGISTER];
GO
IF OBJECT_ID(N'[dbo].[FK_MAGISTEROPEX_OPEX]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[MAGISTEROPEX] DROP CONSTRAINT [FK_MAGISTEROPEX_OPEX];
GO
IF OBJECT_ID(N'[dbo].[FK_DIPLOMADOOPEX_DIPLOMADO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[DIPLOMADOOPEX] DROP CONSTRAINT [FK_DIPLOMADOOPEX_DIPLOMADO];
GO
IF OBJECT_ID(N'[dbo].[FK_DIPLOMADOOPEX_OPEX]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[DIPLOMADOOPEX] DROP CONSTRAINT [FK_DIPLOMADOOPEX_OPEX];
GO
IF OBJECT_ID(N'[dbo].[FK_CARRERAOPEX_CARRERA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[CARRERAOPEX] DROP CONSTRAINT [FK_CARRERAOPEX_CARRERA];
GO
IF OBJECT_ID(N'[dbo].[FK_CARRERAOPEX_OPEX]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[CARRERAOPEX] DROP CONSTRAINT [FK_CARRERAOPEX_OPEX];
GO
IF OBJECT_ID(N'[dbo].[FK_CARRERACAPEX_CARRERA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[CARRERACAPEX] DROP CONSTRAINT [FK_CARRERACAPEX_CARRERA];
GO
IF OBJECT_ID(N'[dbo].[FK_CARRERACAPEX_CAPEX]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[CARRERACAPEX] DROP CONSTRAINT [FK_CARRERACAPEX_CAPEX];
GO
IF OBJECT_ID(N'[dbo].[FK_DIPLOMADOPROP_DIPLOMADO_DIPLOMADO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[DIPLOMADOPROP_DIPLOMADO] DROP CONSTRAINT [FK_DIPLOMADOPROP_DIPLOMADO_DIPLOMADO];
GO
IF OBJECT_ID(N'[dbo].[FK_DIPLOMADOPROP_DIPLOMADO_PROP_DIPLOMADO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[DIPLOMADOPROP_DIPLOMADO] DROP CONSTRAINT [FK_DIPLOMADOPROP_DIPLOMADO_PROP_DIPLOMADO];
GO
IF OBJECT_ID(N'[dbo].[FK_MESPAGO_DIPLOMADO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[MESes] DROP CONSTRAINT [FK_MESPAGO_DIPLOMADO];
GO
IF OBJECT_ID(N'[dbo].[FK_DETALLE_RENDICIONRENDICION_DETALLE_RENDICION]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[DETALLE_RENDICIONRENDICION] DROP CONSTRAINT [FK_DETALLE_RENDICIONRENDICION_DETALLE_RENDICION];
GO
IF OBJECT_ID(N'[dbo].[FK_DETALLE_RENDICIONRENDICION_RENDICION]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[DETALLE_RENDICIONRENDICION] DROP CONSTRAINT [FK_DETALLE_RENDICIONRENDICION_RENDICION];
GO
IF OBJECT_ID(N'[dbo].[FK_PERSONA_JURIDICAs_inherits_PERSONA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[PERSONAs_PERSONA_JURIDICAs] DROP CONSTRAINT [FK_PERSONA_JURIDICAs_inherits_PERSONA];
GO
IF OBJECT_ID(N'[dbo].[FK_PERSONA_NATURALes_inherits_PERSONA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[PERSONAs_PERSONA_NATURALes] DROP CONSTRAINT [FK_PERSONA_NATURALes_inherits_PERSONA];
GO
IF OBJECT_ID(N'[dbo].[FK_CARRERA_inherits_PROGRAMA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[PROGRAMAs_CARRERA] DROP CONSTRAINT [FK_CARRERA_inherits_PROGRAMA];
GO
IF OBJECT_ID(N'[dbo].[FK_DIPLOMADO_inherits_PROGRAMA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[PROGRAMAs_DIPLOMADO] DROP CONSTRAINT [FK_DIPLOMADO_inherits_PROGRAMA];
GO
IF OBJECT_ID(N'[dbo].[FK_MAGISTER_inherits_PROGRAMA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[PROGRAMAs_MAGISTER] DROP CONSTRAINT [FK_MAGISTER_inherits_PROGRAMA];
GO

-- --------------------------------------------------
-- Dropping existing tables
-- --------------------------------------------------

IF OBJECT_ID(N'[dbo].[USUARIOs]', 'U') IS NOT NULL
    DROP TABLE [dbo].[USUARIOs];
GO
IF OBJECT_ID(N'[dbo].[ROLes]', 'U') IS NOT NULL
    DROP TABLE [dbo].[ROLes];
GO
IF OBJECT_ID(N'[dbo].[PROGRAMAs]', 'U') IS NOT NULL
    DROP TABLE [dbo].[PROGRAMAs];
GO
IF OBJECT_ID(N'[dbo].[PERSONAs]', 'U') IS NOT NULL
    DROP TABLE [dbo].[PERSONAs];
GO
IF OBJECT_ID(N'[dbo].[CONSOLIDADOs]', 'U') IS NOT NULL
    DROP TABLE [dbo].[CONSOLIDADOs];
GO
IF OBJECT_ID(N'[dbo].[SALIDA_TERRENOs]', 'U') IS NOT NULL
    DROP TABLE [dbo].[SALIDA_TERRENOs];
GO
IF OBJECT_ID(N'[dbo].[OPEXes]', 'U') IS NOT NULL
    DROP TABLE [dbo].[OPEXes];
GO
IF OBJECT_ID(N'[dbo].[CAPEXes]', 'U') IS NOT NULL
    DROP TABLE [dbo].[CAPEXes];
GO
IF OBJECT_ID(N'[dbo].[PROP_DIPLOMADOs]', 'U') IS NOT NULL
    DROP TABLE [dbo].[PROP_DIPLOMADOs];
GO
IF OBJECT_ID(N'[dbo].[PAGO_DIPLOMADOs]', 'U') IS NOT NULL
    DROP TABLE [dbo].[PAGO_DIPLOMADOs];
GO
IF OBJECT_ID(N'[dbo].[REEMBOLSOs]', 'U') IS NOT NULL
    DROP TABLE [dbo].[REEMBOLSOs];
GO
IF OBJECT_ID(N'[dbo].[RENDICIONes]', 'U') IS NOT NULL
    DROP TABLE [dbo].[RENDICIONes];
GO
IF OBJECT_ID(N'[dbo].[FACTURAs]', 'U') IS NOT NULL
    DROP TABLE [dbo].[FACTURAs];
GO
IF OBJECT_ID(N'[dbo].[BOLETAs]', 'U') IS NOT NULL
    DROP TABLE [dbo].[BOLETAs];
GO
IF OBJECT_ID(N'[dbo].[MESes]', 'U') IS NOT NULL
    DROP TABLE [dbo].[MESes];
GO
IF OBJECT_ID(N'[dbo].[SOLICITUDes]', 'U') IS NOT NULL
    DROP TABLE [dbo].[SOLICITUDes];
GO
IF OBJECT_ID(N'[dbo].[CAMBIOs]', 'U') IS NOT NULL
    DROP TABLE [dbo].[CAMBIOs];
GO
IF OBJECT_ID(N'[dbo].[DETALLE_RENDICION]', 'U') IS NOT NULL
    DROP TABLE [dbo].[DETALLE_RENDICION];
GO
IF OBJECT_ID(N'[dbo].[PERSONAs_PERSONA_JURIDICAs]', 'U') IS NOT NULL
    DROP TABLE [dbo].[PERSONAs_PERSONA_JURIDICAs];
GO
IF OBJECT_ID(N'[dbo].[PERSONAs_PERSONA_NATURALes]', 'U') IS NOT NULL
    DROP TABLE [dbo].[PERSONAs_PERSONA_NATURALes];
GO
IF OBJECT_ID(N'[dbo].[PROGRAMAs_CARRERA]', 'U') IS NOT NULL
    DROP TABLE [dbo].[PROGRAMAs_CARRERA];
GO
IF OBJECT_ID(N'[dbo].[PROGRAMAs_DIPLOMADO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[PROGRAMAs_DIPLOMADO];
GO
IF OBJECT_ID(N'[dbo].[PROGRAMAs_MAGISTER]', 'U') IS NOT NULL
    DROP TABLE [dbo].[PROGRAMAs_MAGISTER];
GO
IF OBJECT_ID(N'[dbo].[SALIDA_TERRENOMES]', 'U') IS NOT NULL
    DROP TABLE [dbo].[SALIDA_TERRENOMES];
GO
IF OBJECT_ID(N'[dbo].[PERSONA_NATURALSOLICITUD]', 'U') IS NOT NULL
    DROP TABLE [dbo].[PERSONA_NATURALSOLICITUD];
GO
IF OBJECT_ID(N'[dbo].[CAMBIOOPEX]', 'U') IS NOT NULL
    DROP TABLE [dbo].[CAMBIOOPEX];
GO
IF OBJECT_ID(N'[dbo].[MAGISTEROPEX]', 'U') IS NOT NULL
    DROP TABLE [dbo].[MAGISTEROPEX];
GO
IF OBJECT_ID(N'[dbo].[DIPLOMADOOPEX]', 'U') IS NOT NULL
    DROP TABLE [dbo].[DIPLOMADOOPEX];
GO
IF OBJECT_ID(N'[dbo].[CARRERAOPEX]', 'U') IS NOT NULL
    DROP TABLE [dbo].[CARRERAOPEX];
GO
IF OBJECT_ID(N'[dbo].[CARRERACAPEX]', 'U') IS NOT NULL
    DROP TABLE [dbo].[CARRERACAPEX];
GO
IF OBJECT_ID(N'[dbo].[DIPLOMADOPROP_DIPLOMADO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[DIPLOMADOPROP_DIPLOMADO];
GO
IF OBJECT_ID(N'[dbo].[DETALLE_RENDICIONRENDICION]', 'U') IS NOT NULL
    DROP TABLE [dbo].[DETALLE_RENDICIONRENDICION];
GO

-- --------------------------------------------------
-- Creating all tables
-- --------------------------------------------------

-- Creating table 'USUARIOs'
CREATE TABLE [dbo].[USUARIOs] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [ESTADO] bit  NOT NULL,
    [NOMBRE_USUARIO] nvarchar(max)  NOT NULL,
    [CONTRASENA] nvarchar(max)  NOT NULL,
    [ROLID] int  NOT NULL
);
GO

-- Creating table 'ROLes'
CREATE TABLE [dbo].[ROLes] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [ESTADO] bit  NOT NULL,
    [NOMBRE_ROL] nvarchar(max)  NOT NULL
);
GO

-- Creating table 'PROGRAMAs'
CREATE TABLE [dbo].[PROGRAMAs] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [ESTADO] bit  NOT NULL,
    [NOMBRE] nvarchar(max)  NOT NULL,
    [U_EXPLOTACION] int  NOT NULL,
    [DEPARTAMENTO] bigint  NOT NULL,
    [PROD_TITULO] int  NOT NULL,
    [DISCIPLINA] bigint  NOT NULL
);
GO

-- Creating table 'PERSONAs'
CREATE TABLE [dbo].[PERSONAs] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [ESTADO] bit  NOT NULL,
    [NOMBRE] nvarchar(max)  NOT NULL,
    [RUT] nvarchar(max)  NOT NULL,
    [DIGITO_VERIFICADOR] nvarchar(max)  NOT NULL
);
GO

-- Creating table 'CONSOLIDADOs'
CREATE TABLE [dbo].[CONSOLIDADOs] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [ESTADO] bit  NOT NULL,
    [MONTO] bigint  NOT NULL,
    [TOTAL] bigint  NOT NULL
);
GO

-- Creating table 'SALIDA_TERRENOs'
CREATE TABLE [dbo].[SALIDA_TERRENOs] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [ESTADO] bit  NOT NULL,
    [TIPO_SALIDA] nvarchar(max)  NOT NULL,
    [UBICACION] nvarchar(max)  NOT NULL,
    [CANTIDAD_ALUMNOS] smallint  NOT NULL
);
GO

-- Creating table 'OPEXes'
CREATE TABLE [dbo].[OPEXes] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [ESTADO] bit  NOT NULL,
    [MONTO_NETO] bigint  NOT NULL,
    [IVA] bigint  NOT NULL,
    [TOTAL] bigint  NOT NULL,
    [ESTADO_OPEX] bit  NOT NULL,
    [RECEPCION] bit  NOT NULL,
    [VALIDACION] bit  NOT NULL,
    [PERSONA_NATURALID] int  NOT NULL
);
GO

-- Creating table 'CAPEXes'
CREATE TABLE [dbo].[CAPEXes] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [ESTADO] bit  NOT NULL,
    [DETALLE] nvarchar(max)  NOT NULL,
    [RECEPCION] bit  NOT NULL,
    [VALIDACION] bit  NOT NULL,
    [PERSONA_JURIDICAID] int  NOT NULL
);
GO

-- Creating table 'PROP_DIPLOMADOs'
CREATE TABLE [dbo].[PROP_DIPLOMADOs] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [ESTADO] bit  NOT NULL,
    [RESPONSABLE] nvarchar(max)  NOT NULL,
    [MODALIDAD] nvarchar(max)  NOT NULL,
    [FECHA_INICIO] datetime  NOT NULL,
    [FECHA_TERMINO] datetime  NOT NULL,
    [CANTIDAD_MODULO] smallint  NOT NULL,
    [CANTIDAD_ALUMNO] smallint  NOT NULL,
    [COSTO] bigint  NOT NULL,
    [INGRESO_NETO] bigint  NOT NULL,
    [COSTO_DOCENTE] bigint  NOT NULL,
    [COSTO_ACADEMICO] bigint  NOT NULL,
    [OTROS_COSTOS] bigint  NOT NULL,
    [TOTAL] bigint  NOT NULL,
    [PERSONA_NATURALID] int  NOT NULL
);
GO

-- Creating table 'PAGO_DIPLOMADOs'
CREATE TABLE [dbo].[PAGO_DIPLOMADOs] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [ESTADO] bit  NOT NULL,
    [PROGRAMA] nvarchar(max)  NOT NULL,
    [MOTIVO] nvarchar(max)  NOT NULL,
    [TOTAL] bigint  NOT NULL,
    [PERSONA_NATURALID] int  NOT NULL
);
GO

-- Creating table 'REEMBOLSOs'
CREATE TABLE [dbo].[REEMBOLSOs] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [ESTADO] bit  NOT NULL,
    [DESCRIPCION] nvarchar(max)  NOT NULL,
    [ESTADO_REEMBOLSO] nvarchar(max)  NOT NULL,
    [FECHA] datetime  NOT NULL,
    [DETALLE] nvarchar(max)  NOT NULL,
    [MONTO] bigint  NOT NULL,
    [TOTAL] bigint  NOT NULL,
    [PERSONA_NATURALID] int  NOT NULL
);
GO

-- Creating table 'RENDICIONes'
CREATE TABLE [dbo].[RENDICIONes] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [ESTADO] bit  NOT NULL,
    [DESCRIPCION] nvarchar(max)  NOT NULL,
    [ESTADO_ANTICIPO] nvarchar(max)  NOT NULL,
    [FECHA] datetime  NOT NULL,
    [ID_RENDICION] int  NOT NULL,
    [DETALLE_VARIOS] nvarchar(max)  NOT NULL,
    [PERSONA_NATURALID] int  NOT NULL,
    [PERSONA_JURIDICAID] int  NOT NULL
);
GO

-- Creating table 'FACTURAs'
CREATE TABLE [dbo].[FACTURAs] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [NUMERO_FACTURA] bigint  NOT NULL,
    [FECHA_FACTURA] datetime  NOT NULL,
    [MONTO] bigint  NOT NULL,
    [DETALLE] nvarchar(max)  NOT NULL,
    [OPEXID] int  NOT NULL,
    [CAPEXID] int  NOT NULL
);
GO

-- Creating table 'BOLETAs'
CREATE TABLE [dbo].[BOLETAs] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [NUMERO_BOLETA] bigint  NOT NULL,
    [FECHA_BOLETA] datetime  NOT NULL,
    [MONTO] bigint  NOT NULL,
    [DETALLE] nvarchar(max)  NOT NULL,
    [OPEXID] int  NOT NULL,
    [CAPEXID] int  NOT NULL
);
GO

-- Creating table 'MESes'
CREATE TABLE [dbo].[MESes] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [NOMBRE_MES] nvarchar(max)  NOT NULL,
    [CONSOLIDADOID] int  NOT NULL,
    [PAGO_DIPLOMADO_ID] int  NOT NULL
);
GO

-- Creating table 'SOLICITUDes'
CREATE TABLE [dbo].[SOLICITUDes] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [NUMERO_SOLICITUD] bigint  NOT NULL,
    [DETALLE] nvarchar(max)  NOT NULL,
    [PERSONA_JURIDICAID] int  NOT NULL,
    [CAPEXID] int  NOT NULL,
    [OPEXID] int  NOT NULL
);
GO

-- Creating table 'CAMBIOs'
CREATE TABLE [dbo].[CAMBIOs] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [MONEDA_CAMBIO] nvarchar(max)  NOT NULL,
    [FECHA] datetime  NOT NULL
);
GO

-- Creating table 'DETALLE_RENDICION'
CREATE TABLE [dbo].[DETALLE_RENDICION] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [CODIGO] bigint  NOT NULL,
    [NOMBRE_ORGANIZACION] nvarchar(max)  NOT NULL,
    [MONTO] bigint  NOT NULL
);
GO

-- Creating table 'PERSONAs_PERSONA_JURIDICAs'
CREATE TABLE [dbo].[PERSONAs_PERSONA_JURIDICAs] (
    [ID] int  NOT NULL
);
GO

-- Creating table 'PERSONAs_PERSONA_NATURALes'
CREATE TABLE [dbo].[PERSONAs_PERSONA_NATURALes] (
    [APELLIDO_PATERNO] nvarchar(max)  NOT NULL,
    [APELLIDO_MATERNO] nvarchar(max)  NOT NULL,
    [ID_EMPLEADO] bigint  NOT NULL,
    [CORREO] nvarchar(max)  NOT NULL,
    [ID] int  NOT NULL
);
GO

-- Creating table 'PROGRAMAs_CARRERA'
CREATE TABLE [dbo].[PROGRAMAs_CARRERA] (
    [CONSOLIDADOID] int  NOT NULL,
    [ID] int  NOT NULL
);
GO

-- Creating table 'PROGRAMAs_DIPLOMADO'
CREATE TABLE [dbo].[PROGRAMAs_DIPLOMADO] (
    [ACTIVITY_CODE] bigint  NOT NULL,
    [CONSOLIDADOID] int  NOT NULL,
    [ID] int  NOT NULL
);
GO

-- Creating table 'PROGRAMAs_MAGISTER'
CREATE TABLE [dbo].[PROGRAMAs_MAGISTER] (
    [CONSOLIDADOID] int  NOT NULL,
    [ID] int  NOT NULL
);
GO

-- Creating table 'SALIDA_TERRENOMES'
CREATE TABLE [dbo].[SALIDA_TERRENOMES] (
    [SALIDA_TERRENO_ID] int  NOT NULL,
    [MES_ID] int  NOT NULL
);
GO

-- Creating table 'PERSONA_NATURALSOLICITUD'
CREATE TABLE [dbo].[PERSONA_NATURALSOLICITUD] (
    [PERSONA_NATURAL_ID] int  NOT NULL,
    [SOLICITUDs_ID] int  NOT NULL
);
GO

-- Creating table 'CAMBIOOPEX'
CREATE TABLE [dbo].[CAMBIOOPEX] (
    [CAMBIOs_ID] int  NOT NULL,
    [OPEXes_ID] int  NOT NULL
);
GO

-- Creating table 'MAGISTEROPEX'
CREATE TABLE [dbo].[MAGISTEROPEX] (
    [MAGISTERs_ID] int  NOT NULL,
    [OPEXes_ID] int  NOT NULL
);
GO

-- Creating table 'DIPLOMADOOPEX'
CREATE TABLE [dbo].[DIPLOMADOOPEX] (
    [DIPLOMADOes_ID] int  NOT NULL,
    [OPEXes_ID] int  NOT NULL
);
GO

-- Creating table 'CARRERAOPEX'
CREATE TABLE [dbo].[CARRERAOPEX] (
    [CARRERAs_ID] int  NOT NULL,
    [OPEXes_ID] int  NOT NULL
);
GO

-- Creating table 'CARRERACAPEX'
CREATE TABLE [dbo].[CARRERACAPEX] (
    [CARRERAs_ID] int  NOT NULL,
    [CAPEXes_ID] int  NOT NULL
);
GO

-- Creating table 'DIPLOMADOPROP_DIPLOMADO'
CREATE TABLE [dbo].[DIPLOMADOPROP_DIPLOMADO] (
    [DIPLOMADOes_ID] int  NOT NULL,
    [PROP_DIPLOMADO_ID] int  NOT NULL
);
GO

-- Creating table 'DETALLE_RENDICIONRENDICION'
CREATE TABLE [dbo].[DETALLE_RENDICIONRENDICION] (
    [DETALLE_RENDICION_ID] int  NOT NULL,
    [RENDICIONs_ID] int  NOT NULL
);
GO

-- --------------------------------------------------
-- Creating all PRIMARY KEY constraints
-- --------------------------------------------------

-- Creating primary key on [ID] in table 'USUARIOs'
ALTER TABLE [dbo].[USUARIOs]
ADD CONSTRAINT [PK_USUARIOs]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'ROLes'
ALTER TABLE [dbo].[ROLes]
ADD CONSTRAINT [PK_ROLes]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'PROGRAMAs'
ALTER TABLE [dbo].[PROGRAMAs]
ADD CONSTRAINT [PK_PROGRAMAs]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'PERSONAs'
ALTER TABLE [dbo].[PERSONAs]
ADD CONSTRAINT [PK_PERSONAs]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'CONSOLIDADOs'
ALTER TABLE [dbo].[CONSOLIDADOs]
ADD CONSTRAINT [PK_CONSOLIDADOs]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'SALIDA_TERRENOs'
ALTER TABLE [dbo].[SALIDA_TERRENOs]
ADD CONSTRAINT [PK_SALIDA_TERRENOs]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'OPEXes'
ALTER TABLE [dbo].[OPEXes]
ADD CONSTRAINT [PK_OPEXes]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'CAPEXes'
ALTER TABLE [dbo].[CAPEXes]
ADD CONSTRAINT [PK_CAPEXes]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'PROP_DIPLOMADOs'
ALTER TABLE [dbo].[PROP_DIPLOMADOs]
ADD CONSTRAINT [PK_PROP_DIPLOMADOs]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'PAGO_DIPLOMADOs'
ALTER TABLE [dbo].[PAGO_DIPLOMADOs]
ADD CONSTRAINT [PK_PAGO_DIPLOMADOs]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'REEMBOLSOs'
ALTER TABLE [dbo].[REEMBOLSOs]
ADD CONSTRAINT [PK_REEMBOLSOs]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'RENDICIONes'
ALTER TABLE [dbo].[RENDICIONes]
ADD CONSTRAINT [PK_RENDICIONes]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'FACTURAs'
ALTER TABLE [dbo].[FACTURAs]
ADD CONSTRAINT [PK_FACTURAs]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'BOLETAs'
ALTER TABLE [dbo].[BOLETAs]
ADD CONSTRAINT [PK_BOLETAs]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'MESes'
ALTER TABLE [dbo].[MESes]
ADD CONSTRAINT [PK_MESes]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'SOLICITUDes'
ALTER TABLE [dbo].[SOLICITUDes]
ADD CONSTRAINT [PK_SOLICITUDes]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'CAMBIOs'
ALTER TABLE [dbo].[CAMBIOs]
ADD CONSTRAINT [PK_CAMBIOs]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'DETALLE_RENDICION'
ALTER TABLE [dbo].[DETALLE_RENDICION]
ADD CONSTRAINT [PK_DETALLE_RENDICION]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'PERSONAs_PERSONA_JURIDICAs'
ALTER TABLE [dbo].[PERSONAs_PERSONA_JURIDICAs]
ADD CONSTRAINT [PK_PERSONAs_PERSONA_JURIDICAs]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'PERSONAs_PERSONA_NATURALes'
ALTER TABLE [dbo].[PERSONAs_PERSONA_NATURALes]
ADD CONSTRAINT [PK_PERSONAs_PERSONA_NATURALes]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'PROGRAMAs_CARRERA'
ALTER TABLE [dbo].[PROGRAMAs_CARRERA]
ADD CONSTRAINT [PK_PROGRAMAs_CARRERA]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'PROGRAMAs_DIPLOMADO'
ALTER TABLE [dbo].[PROGRAMAs_DIPLOMADO]
ADD CONSTRAINT [PK_PROGRAMAs_DIPLOMADO]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'PROGRAMAs_MAGISTER'
ALTER TABLE [dbo].[PROGRAMAs_MAGISTER]
ADD CONSTRAINT [PK_PROGRAMAs_MAGISTER]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [SALIDA_TERRENO_ID], [MES_ID] in table 'SALIDA_TERRENOMES'
ALTER TABLE [dbo].[SALIDA_TERRENOMES]
ADD CONSTRAINT [PK_SALIDA_TERRENOMES]
    PRIMARY KEY CLUSTERED ([SALIDA_TERRENO_ID], [MES_ID] ASC);
GO

-- Creating primary key on [PERSONA_NATURAL_ID], [SOLICITUDs_ID] in table 'PERSONA_NATURALSOLICITUD'
ALTER TABLE [dbo].[PERSONA_NATURALSOLICITUD]
ADD CONSTRAINT [PK_PERSONA_NATURALSOLICITUD]
    PRIMARY KEY CLUSTERED ([PERSONA_NATURAL_ID], [SOLICITUDs_ID] ASC);
GO

-- Creating primary key on [CAMBIOs_ID], [OPEXes_ID] in table 'CAMBIOOPEX'
ALTER TABLE [dbo].[CAMBIOOPEX]
ADD CONSTRAINT [PK_CAMBIOOPEX]
    PRIMARY KEY CLUSTERED ([CAMBIOs_ID], [OPEXes_ID] ASC);
GO

-- Creating primary key on [MAGISTERs_ID], [OPEXes_ID] in table 'MAGISTEROPEX'
ALTER TABLE [dbo].[MAGISTEROPEX]
ADD CONSTRAINT [PK_MAGISTEROPEX]
    PRIMARY KEY CLUSTERED ([MAGISTERs_ID], [OPEXes_ID] ASC);
GO

-- Creating primary key on [DIPLOMADOes_ID], [OPEXes_ID] in table 'DIPLOMADOOPEX'
ALTER TABLE [dbo].[DIPLOMADOOPEX]
ADD CONSTRAINT [PK_DIPLOMADOOPEX]
    PRIMARY KEY CLUSTERED ([DIPLOMADOes_ID], [OPEXes_ID] ASC);
GO

-- Creating primary key on [CARRERAs_ID], [OPEXes_ID] in table 'CARRERAOPEX'
ALTER TABLE [dbo].[CARRERAOPEX]
ADD CONSTRAINT [PK_CARRERAOPEX]
    PRIMARY KEY CLUSTERED ([CARRERAs_ID], [OPEXes_ID] ASC);
GO

-- Creating primary key on [CARRERAs_ID], [CAPEXes_ID] in table 'CARRERACAPEX'
ALTER TABLE [dbo].[CARRERACAPEX]
ADD CONSTRAINT [PK_CARRERACAPEX]
    PRIMARY KEY CLUSTERED ([CARRERAs_ID], [CAPEXes_ID] ASC);
GO

-- Creating primary key on [DIPLOMADOes_ID], [PROP_DIPLOMADO_ID] in table 'DIPLOMADOPROP_DIPLOMADO'
ALTER TABLE [dbo].[DIPLOMADOPROP_DIPLOMADO]
ADD CONSTRAINT [PK_DIPLOMADOPROP_DIPLOMADO]
    PRIMARY KEY CLUSTERED ([DIPLOMADOes_ID], [PROP_DIPLOMADO_ID] ASC);
GO

-- Creating primary key on [DETALLE_RENDICION_ID], [RENDICIONs_ID] in table 'DETALLE_RENDICIONRENDICION'
ALTER TABLE [dbo].[DETALLE_RENDICIONRENDICION]
ADD CONSTRAINT [PK_DETALLE_RENDICIONRENDICION]
    PRIMARY KEY CLUSTERED ([DETALLE_RENDICION_ID], [RENDICIONs_ID] ASC);
GO

-- --------------------------------------------------
-- Creating all FOREIGN KEY constraints
-- --------------------------------------------------

-- Creating foreign key on [ROLID] in table 'USUARIOs'
ALTER TABLE [dbo].[USUARIOs]
ADD CONSTRAINT [FK_USUARIOROL]
    FOREIGN KEY ([ROLID])
    REFERENCES [dbo].[ROLes]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_USUARIOROL'
CREATE INDEX [IX_FK_USUARIOROL]
ON [dbo].[USUARIOs]
    ([ROLID]);
GO

-- Creating foreign key on [PERSONA_JURIDICAID] in table 'RENDICIONes'
ALTER TABLE [dbo].[RENDICIONes]
ADD CONSTRAINT [FK_PERSONA_JURIDICARENDICION]
    FOREIGN KEY ([PERSONA_JURIDICAID])
    REFERENCES [dbo].[PERSONAs_PERSONA_JURIDICAs]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_PERSONA_JURIDICARENDICION'
CREATE INDEX [IX_FK_PERSONA_JURIDICARENDICION]
ON [dbo].[RENDICIONes]
    ([PERSONA_JURIDICAID]);
GO

-- Creating foreign key on [PERSONA_JURIDICAID] in table 'CAPEXes'
ALTER TABLE [dbo].[CAPEXes]
ADD CONSTRAINT [FK_PERSONA_JURIDICACAPEX]
    FOREIGN KEY ([PERSONA_JURIDICAID])
    REFERENCES [dbo].[PERSONAs_PERSONA_JURIDICAs]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_PERSONA_JURIDICACAPEX'
CREATE INDEX [IX_FK_PERSONA_JURIDICACAPEX]
ON [dbo].[CAPEXes]
    ([PERSONA_JURIDICAID]);
GO

-- Creating foreign key on [PERSONA_NATURALID] in table 'OPEXes'
ALTER TABLE [dbo].[OPEXes]
ADD CONSTRAINT [FK_PERSONA_NATURALOPEX]
    FOREIGN KEY ([PERSONA_NATURALID])
    REFERENCES [dbo].[PERSONAs_PERSONA_NATURALes]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_PERSONA_NATURALOPEX'
CREATE INDEX [IX_FK_PERSONA_NATURALOPEX]
ON [dbo].[OPEXes]
    ([PERSONA_NATURALID]);
GO

-- Creating foreign key on [PERSONA_NATURALID] in table 'PROP_DIPLOMADOs'
ALTER TABLE [dbo].[PROP_DIPLOMADOs]
ADD CONSTRAINT [FK_PERSONA_NATURALPROP_DIPLOMADO]
    FOREIGN KEY ([PERSONA_NATURALID])
    REFERENCES [dbo].[PERSONAs_PERSONA_NATURALes]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_PERSONA_NATURALPROP_DIPLOMADO'
CREATE INDEX [IX_FK_PERSONA_NATURALPROP_DIPLOMADO]
ON [dbo].[PROP_DIPLOMADOs]
    ([PERSONA_NATURALID]);
GO

-- Creating foreign key on [PERSONA_NATURALID] in table 'PAGO_DIPLOMADOs'
ALTER TABLE [dbo].[PAGO_DIPLOMADOs]
ADD CONSTRAINT [FK_PERSONA_NATURALPAGO_DIPLOMADO]
    FOREIGN KEY ([PERSONA_NATURALID])
    REFERENCES [dbo].[PERSONAs_PERSONA_NATURALes]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_PERSONA_NATURALPAGO_DIPLOMADO'
CREATE INDEX [IX_FK_PERSONA_NATURALPAGO_DIPLOMADO]
ON [dbo].[PAGO_DIPLOMADOs]
    ([PERSONA_NATURALID]);
GO

-- Creating foreign key on [PERSONA_NATURALID] in table 'REEMBOLSOs'
ALTER TABLE [dbo].[REEMBOLSOs]
ADD CONSTRAINT [FK_PERSONA_NATURALREEMBOLSO]
    FOREIGN KEY ([PERSONA_NATURALID])
    REFERENCES [dbo].[PERSONAs_PERSONA_NATURALes]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_PERSONA_NATURALREEMBOLSO'
CREATE INDEX [IX_FK_PERSONA_NATURALREEMBOLSO]
ON [dbo].[REEMBOLSOs]
    ([PERSONA_NATURALID]);
GO

-- Creating foreign key on [PERSONA_NATURALID] in table 'RENDICIONes'
ALTER TABLE [dbo].[RENDICIONes]
ADD CONSTRAINT [FK_PERSONA_NATURALRENDICION]
    FOREIGN KEY ([PERSONA_NATURALID])
    REFERENCES [dbo].[PERSONAs_PERSONA_NATURALes]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_PERSONA_NATURALRENDICION'
CREATE INDEX [IX_FK_PERSONA_NATURALRENDICION]
ON [dbo].[RENDICIONes]
    ([PERSONA_NATURALID]);
GO

-- Creating foreign key on [OPEXID] in table 'FACTURAs'
ALTER TABLE [dbo].[FACTURAs]
ADD CONSTRAINT [FK_OPEXFACTURA]
    FOREIGN KEY ([OPEXID])
    REFERENCES [dbo].[OPEXes]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_OPEXFACTURA'
CREATE INDEX [IX_FK_OPEXFACTURA]
ON [dbo].[FACTURAs]
    ([OPEXID]);
GO

-- Creating foreign key on [OPEXID] in table 'BOLETAs'
ALTER TABLE [dbo].[BOLETAs]
ADD CONSTRAINT [FK_OPEXBOLETA]
    FOREIGN KEY ([OPEXID])
    REFERENCES [dbo].[OPEXes]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_OPEXBOLETA'
CREATE INDEX [IX_FK_OPEXBOLETA]
ON [dbo].[BOLETAs]
    ([OPEXID]);
GO

-- Creating foreign key on [CAPEXID] in table 'BOLETAs'
ALTER TABLE [dbo].[BOLETAs]
ADD CONSTRAINT [FK_CAPEXBOLETA]
    FOREIGN KEY ([CAPEXID])
    REFERENCES [dbo].[CAPEXes]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_CAPEXBOLETA'
CREATE INDEX [IX_FK_CAPEXBOLETA]
ON [dbo].[BOLETAs]
    ([CAPEXID]);
GO

-- Creating foreign key on [CAPEXID] in table 'FACTURAs'
ALTER TABLE [dbo].[FACTURAs]
ADD CONSTRAINT [FK_CAPEXFACTURA]
    FOREIGN KEY ([CAPEXID])
    REFERENCES [dbo].[CAPEXes]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_CAPEXFACTURA'
CREATE INDEX [IX_FK_CAPEXFACTURA]
ON [dbo].[FACTURAs]
    ([CAPEXID]);
GO

-- Creating foreign key on [CONSOLIDADOID] in table 'PROGRAMAs_CARRERA'
ALTER TABLE [dbo].[PROGRAMAs_CARRERA]
ADD CONSTRAINT [FK_CONSOLIDADOCARRERA]
    FOREIGN KEY ([CONSOLIDADOID])
    REFERENCES [dbo].[CONSOLIDADOs]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_CONSOLIDADOCARRERA'
CREATE INDEX [IX_FK_CONSOLIDADOCARRERA]
ON [dbo].[PROGRAMAs_CARRERA]
    ([CONSOLIDADOID]);
GO

-- Creating foreign key on [CONSOLIDADOID] in table 'PROGRAMAs_DIPLOMADO'
ALTER TABLE [dbo].[PROGRAMAs_DIPLOMADO]
ADD CONSTRAINT [FK_CONSOLIDADODIPLOMADO]
    FOREIGN KEY ([CONSOLIDADOID])
    REFERENCES [dbo].[CONSOLIDADOs]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_CONSOLIDADODIPLOMADO'
CREATE INDEX [IX_FK_CONSOLIDADODIPLOMADO]
ON [dbo].[PROGRAMAs_DIPLOMADO]
    ([CONSOLIDADOID]);
GO

-- Creating foreign key on [CONSOLIDADOID] in table 'PROGRAMAs_MAGISTER'
ALTER TABLE [dbo].[PROGRAMAs_MAGISTER]
ADD CONSTRAINT [FK_CONSOLIDADOMAGISTER]
    FOREIGN KEY ([CONSOLIDADOID])
    REFERENCES [dbo].[CONSOLIDADOs]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_CONSOLIDADOMAGISTER'
CREATE INDEX [IX_FK_CONSOLIDADOMAGISTER]
ON [dbo].[PROGRAMAs_MAGISTER]
    ([CONSOLIDADOID]);
GO

-- Creating foreign key on [CONSOLIDADOID] in table 'MESes'
ALTER TABLE [dbo].[MESes]
ADD CONSTRAINT [FK_CONSOLIDADOMES]
    FOREIGN KEY ([CONSOLIDADOID])
    REFERENCES [dbo].[CONSOLIDADOs]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_CONSOLIDADOMES'
CREATE INDEX [IX_FK_CONSOLIDADOMES]
ON [dbo].[MESes]
    ([CONSOLIDADOID]);
GO

-- Creating foreign key on [SALIDA_TERRENO_ID] in table 'SALIDA_TERRENOMES'
ALTER TABLE [dbo].[SALIDA_TERRENOMES]
ADD CONSTRAINT [FK_SALIDA_TERRENOMES_SALIDA_TERRENO]
    FOREIGN KEY ([SALIDA_TERRENO_ID])
    REFERENCES [dbo].[SALIDA_TERRENOs]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating foreign key on [MES_ID] in table 'SALIDA_TERRENOMES'
ALTER TABLE [dbo].[SALIDA_TERRENOMES]
ADD CONSTRAINT [FK_SALIDA_TERRENOMES_MES]
    FOREIGN KEY ([MES_ID])
    REFERENCES [dbo].[MESes]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_SALIDA_TERRENOMES_MES'
CREATE INDEX [IX_FK_SALIDA_TERRENOMES_MES]
ON [dbo].[SALIDA_TERRENOMES]
    ([MES_ID]);
GO

-- Creating foreign key on [PERSONA_JURIDICAID] in table 'SOLICITUDes'
ALTER TABLE [dbo].[SOLICITUDes]
ADD CONSTRAINT [FK_PERSONA_JURIDICASOLICITUD]
    FOREIGN KEY ([PERSONA_JURIDICAID])
    REFERENCES [dbo].[PERSONAs_PERSONA_JURIDICAs]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_PERSONA_JURIDICASOLICITUD'
CREATE INDEX [IX_FK_PERSONA_JURIDICASOLICITUD]
ON [dbo].[SOLICITUDes]
    ([PERSONA_JURIDICAID]);
GO

-- Creating foreign key on [CAPEXID] in table 'SOLICITUDes'
ALTER TABLE [dbo].[SOLICITUDes]
ADD CONSTRAINT [FK_SOLICITUDCAPEX]
    FOREIGN KEY ([CAPEXID])
    REFERENCES [dbo].[CAPEXes]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_SOLICITUDCAPEX'
CREATE INDEX [IX_FK_SOLICITUDCAPEX]
ON [dbo].[SOLICITUDes]
    ([CAPEXID]);
GO

-- Creating foreign key on [OPEXID] in table 'SOLICITUDes'
ALTER TABLE [dbo].[SOLICITUDes]
ADD CONSTRAINT [FK_SOLICITUDOPEX]
    FOREIGN KEY ([OPEXID])
    REFERENCES [dbo].[OPEXes]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_SOLICITUDOPEX'
CREATE INDEX [IX_FK_SOLICITUDOPEX]
ON [dbo].[SOLICITUDes]
    ([OPEXID]);
GO

-- Creating foreign key on [PERSONA_NATURAL_ID] in table 'PERSONA_NATURALSOLICITUD'
ALTER TABLE [dbo].[PERSONA_NATURALSOLICITUD]
ADD CONSTRAINT [FK_PERSONA_NATURALSOLICITUD_PERSONA_NATURAL]
    FOREIGN KEY ([PERSONA_NATURAL_ID])
    REFERENCES [dbo].[PERSONAs_PERSONA_NATURALes]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating foreign key on [SOLICITUDs_ID] in table 'PERSONA_NATURALSOLICITUD'
ALTER TABLE [dbo].[PERSONA_NATURALSOLICITUD]
ADD CONSTRAINT [FK_PERSONA_NATURALSOLICITUD_SOLICITUD]
    FOREIGN KEY ([SOLICITUDs_ID])
    REFERENCES [dbo].[SOLICITUDes]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_PERSONA_NATURALSOLICITUD_SOLICITUD'
CREATE INDEX [IX_FK_PERSONA_NATURALSOLICITUD_SOLICITUD]
ON [dbo].[PERSONA_NATURALSOLICITUD]
    ([SOLICITUDs_ID]);
GO

-- Creating foreign key on [CAMBIOs_ID] in table 'CAMBIOOPEX'
ALTER TABLE [dbo].[CAMBIOOPEX]
ADD CONSTRAINT [FK_CAMBIOOPEX_CAMBIO]
    FOREIGN KEY ([CAMBIOs_ID])
    REFERENCES [dbo].[CAMBIOs]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating foreign key on [OPEXes_ID] in table 'CAMBIOOPEX'
ALTER TABLE [dbo].[CAMBIOOPEX]
ADD CONSTRAINT [FK_CAMBIOOPEX_OPEX]
    FOREIGN KEY ([OPEXes_ID])
    REFERENCES [dbo].[OPEXes]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_CAMBIOOPEX_OPEX'
CREATE INDEX [IX_FK_CAMBIOOPEX_OPEX]
ON [dbo].[CAMBIOOPEX]
    ([OPEXes_ID]);
GO

-- Creating foreign key on [MAGISTERs_ID] in table 'MAGISTEROPEX'
ALTER TABLE [dbo].[MAGISTEROPEX]
ADD CONSTRAINT [FK_MAGISTEROPEX_MAGISTER]
    FOREIGN KEY ([MAGISTERs_ID])
    REFERENCES [dbo].[PROGRAMAs_MAGISTER]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating foreign key on [OPEXes_ID] in table 'MAGISTEROPEX'
ALTER TABLE [dbo].[MAGISTEROPEX]
ADD CONSTRAINT [FK_MAGISTEROPEX_OPEX]
    FOREIGN KEY ([OPEXes_ID])
    REFERENCES [dbo].[OPEXes]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_MAGISTEROPEX_OPEX'
CREATE INDEX [IX_FK_MAGISTEROPEX_OPEX]
ON [dbo].[MAGISTEROPEX]
    ([OPEXes_ID]);
GO

-- Creating foreign key on [DIPLOMADOes_ID] in table 'DIPLOMADOOPEX'
ALTER TABLE [dbo].[DIPLOMADOOPEX]
ADD CONSTRAINT [FK_DIPLOMADOOPEX_DIPLOMADO]
    FOREIGN KEY ([DIPLOMADOes_ID])
    REFERENCES [dbo].[PROGRAMAs_DIPLOMADO]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating foreign key on [OPEXes_ID] in table 'DIPLOMADOOPEX'
ALTER TABLE [dbo].[DIPLOMADOOPEX]
ADD CONSTRAINT [FK_DIPLOMADOOPEX_OPEX]
    FOREIGN KEY ([OPEXes_ID])
    REFERENCES [dbo].[OPEXes]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_DIPLOMADOOPEX_OPEX'
CREATE INDEX [IX_FK_DIPLOMADOOPEX_OPEX]
ON [dbo].[DIPLOMADOOPEX]
    ([OPEXes_ID]);
GO

-- Creating foreign key on [CARRERAs_ID] in table 'CARRERAOPEX'
ALTER TABLE [dbo].[CARRERAOPEX]
ADD CONSTRAINT [FK_CARRERAOPEX_CARRERA]
    FOREIGN KEY ([CARRERAs_ID])
    REFERENCES [dbo].[PROGRAMAs_CARRERA]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating foreign key on [OPEXes_ID] in table 'CARRERAOPEX'
ALTER TABLE [dbo].[CARRERAOPEX]
ADD CONSTRAINT [FK_CARRERAOPEX_OPEX]
    FOREIGN KEY ([OPEXes_ID])
    REFERENCES [dbo].[OPEXes]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_CARRERAOPEX_OPEX'
CREATE INDEX [IX_FK_CARRERAOPEX_OPEX]
ON [dbo].[CARRERAOPEX]
    ([OPEXes_ID]);
GO

-- Creating foreign key on [CARRERAs_ID] in table 'CARRERACAPEX'
ALTER TABLE [dbo].[CARRERACAPEX]
ADD CONSTRAINT [FK_CARRERACAPEX_CARRERA]
    FOREIGN KEY ([CARRERAs_ID])
    REFERENCES [dbo].[PROGRAMAs_CARRERA]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating foreign key on [CAPEXes_ID] in table 'CARRERACAPEX'
ALTER TABLE [dbo].[CARRERACAPEX]
ADD CONSTRAINT [FK_CARRERACAPEX_CAPEX]
    FOREIGN KEY ([CAPEXes_ID])
    REFERENCES [dbo].[CAPEXes]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_CARRERACAPEX_CAPEX'
CREATE INDEX [IX_FK_CARRERACAPEX_CAPEX]
ON [dbo].[CARRERACAPEX]
    ([CAPEXes_ID]);
GO

-- Creating foreign key on [DIPLOMADOes_ID] in table 'DIPLOMADOPROP_DIPLOMADO'
ALTER TABLE [dbo].[DIPLOMADOPROP_DIPLOMADO]
ADD CONSTRAINT [FK_DIPLOMADOPROP_DIPLOMADO_DIPLOMADO]
    FOREIGN KEY ([DIPLOMADOes_ID])
    REFERENCES [dbo].[PROGRAMAs_DIPLOMADO]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating foreign key on [PROP_DIPLOMADO_ID] in table 'DIPLOMADOPROP_DIPLOMADO'
ALTER TABLE [dbo].[DIPLOMADOPROP_DIPLOMADO]
ADD CONSTRAINT [FK_DIPLOMADOPROP_DIPLOMADO_PROP_DIPLOMADO]
    FOREIGN KEY ([PROP_DIPLOMADO_ID])
    REFERENCES [dbo].[PROP_DIPLOMADOs]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_DIPLOMADOPROP_DIPLOMADO_PROP_DIPLOMADO'
CREATE INDEX [IX_FK_DIPLOMADOPROP_DIPLOMADO_PROP_DIPLOMADO]
ON [dbo].[DIPLOMADOPROP_DIPLOMADO]
    ([PROP_DIPLOMADO_ID]);
GO

-- Creating foreign key on [PAGO_DIPLOMADO_ID] in table 'MESes'
ALTER TABLE [dbo].[MESes]
ADD CONSTRAINT [FK_MESPAGO_DIPLOMADO]
    FOREIGN KEY ([PAGO_DIPLOMADO_ID])
    REFERENCES [dbo].[PAGO_DIPLOMADOs]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_MESPAGO_DIPLOMADO'
CREATE INDEX [IX_FK_MESPAGO_DIPLOMADO]
ON [dbo].[MESes]
    ([PAGO_DIPLOMADO_ID]);
GO

-- Creating foreign key on [DETALLE_RENDICION_ID] in table 'DETALLE_RENDICIONRENDICION'
ALTER TABLE [dbo].[DETALLE_RENDICIONRENDICION]
ADD CONSTRAINT [FK_DETALLE_RENDICIONRENDICION_DETALLE_RENDICION]
    FOREIGN KEY ([DETALLE_RENDICION_ID])
    REFERENCES [dbo].[DETALLE_RENDICION]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating foreign key on [RENDICIONs_ID] in table 'DETALLE_RENDICIONRENDICION'
ALTER TABLE [dbo].[DETALLE_RENDICIONRENDICION]
ADD CONSTRAINT [FK_DETALLE_RENDICIONRENDICION_RENDICION]
    FOREIGN KEY ([RENDICIONs_ID])
    REFERENCES [dbo].[RENDICIONes]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_DETALLE_RENDICIONRENDICION_RENDICION'
CREATE INDEX [IX_FK_DETALLE_RENDICIONRENDICION_RENDICION]
ON [dbo].[DETALLE_RENDICIONRENDICION]
    ([RENDICIONs_ID]);
GO

-- Creating foreign key on [ID] in table 'PERSONAs_PERSONA_JURIDICAs'
ALTER TABLE [dbo].[PERSONAs_PERSONA_JURIDICAs]
ADD CONSTRAINT [FK_PERSONA_JURIDICAs_inherits_PERSONA]
    FOREIGN KEY ([ID])
    REFERENCES [dbo].[PERSONAs]
        ([ID])
    ON DELETE CASCADE ON UPDATE NO ACTION;
GO

-- Creating foreign key on [ID] in table 'PERSONAs_PERSONA_NATURALes'
ALTER TABLE [dbo].[PERSONAs_PERSONA_NATURALes]
ADD CONSTRAINT [FK_PERSONA_NATURALes_inherits_PERSONA]
    FOREIGN KEY ([ID])
    REFERENCES [dbo].[PERSONAs]
        ([ID])
    ON DELETE CASCADE ON UPDATE NO ACTION;
GO

-- Creating foreign key on [ID] in table 'PROGRAMAs_CARRERA'
ALTER TABLE [dbo].[PROGRAMAs_CARRERA]
ADD CONSTRAINT [FK_CARRERA_inherits_PROGRAMA]
    FOREIGN KEY ([ID])
    REFERENCES [dbo].[PROGRAMAs]
        ([ID])
    ON DELETE CASCADE ON UPDATE NO ACTION;
GO

-- Creating foreign key on [ID] in table 'PROGRAMAs_DIPLOMADO'
ALTER TABLE [dbo].[PROGRAMAs_DIPLOMADO]
ADD CONSTRAINT [FK_DIPLOMADO_inherits_PROGRAMA]
    FOREIGN KEY ([ID])
    REFERENCES [dbo].[PROGRAMAs]
        ([ID])
    ON DELETE CASCADE ON UPDATE NO ACTION;
GO

-- Creating foreign key on [ID] in table 'PROGRAMAs_MAGISTER'
ALTER TABLE [dbo].[PROGRAMAs_MAGISTER]
ADD CONSTRAINT [FK_MAGISTER_inherits_PROGRAMA]
    FOREIGN KEY ([ID])
    REFERENCES [dbo].[PROGRAMAs]
        ([ID])
    ON DELETE CASCADE ON UPDATE NO ACTION;
GO

-- --------------------------------------------------
-- Script has ended
-- --------------------------------------------------