//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_UVM_Control_Presupuestario
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPEX
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPEX()
        {
            this.FACTURAs = new HashSet<FACTURA>();
            this.BOLETAs = new HashSet<BOLETA>();
            this.SOLICITUDs = new HashSet<SOLICITUD>();
            this.CAMBIOs = new HashSet<CAMBIO>();
            this.MAGISTERs = new HashSet<MAGISTER>();
            this.DIPLOMADOes = new HashSet<DIPLOMADO>();
            this.CARRERAs = new HashSet<CARRERA>();
        }
    
        public int ID { get; set; }
        public bool ESTADO { get; set; }
        public long MONTO_NETO { get; set; }
        public long IVA { get; set; }
        public long TOTAL { get; set; }
        public bool ESTADO_OPEX { get; set; }
        public bool RECEPCION { get; set; }
        public bool VALIDACION { get; set; }
        public int PERSONA_NATURALID { get; set; }
    
        public virtual PERSONA_NATURALes PERSONA_NATURAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURA> FACTURAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOLETA> BOLETAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLICITUD> SOLICITUDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAMBIO> CAMBIOs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAGISTER> MAGISTERs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIPLOMADO> DIPLOMADOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARRERA> CARRERAs { get; set; }
    }
}
