//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_UVM_Control_Presupuestario
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROGRAMA
    {
        public int ID { get; set; }
        public bool ESTADO { get; set; }
        public string NOMBRE { get; set; }
        public int U_EXPLOTACION { get; set; }
        public long DEPARTAMENTO { get; set; }
        public int PROD_TITULO { get; set; }
        public long DISCIPLINA { get; set; }
    }
}
