//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_UVM_Control_Presupuestario
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROP_DIPLOMADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROP_DIPLOMADO()
        {
            this.DIPLOMADOes = new HashSet<DIPLOMADO>();
        }
    
        public int ID { get; set; }
        public bool ESTADO { get; set; }
        public string RESPONSABLE { get; set; }
        public string MODALIDAD { get; set; }
        public System.DateTime FECHA_INICIO { get; set; }
        public System.DateTime FECHA_TERMINO { get; set; }
        public short CANTIDAD_MODULO { get; set; }
        public short CANTIDAD_ALUMNO { get; set; }
        public long COSTO { get; set; }
        public long INGRESO_NETO { get; set; }
        public long COSTO_DOCENTE { get; set; }
        public long COSTO_ACADEMICO { get; set; }
        public long OTROS_COSTOS { get; set; }
        public long TOTAL { get; set; }
        public int PERSONA_NATURALID { get; set; }
    
        public virtual PERSONA_NATURALes PERSONA_NATURAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIPLOMADO> DIPLOMADOes { get; set; }
    }
}
