//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_UVM_Control_Presupuestario
{
    using System;
    using System.Collections.Generic;
    
    public partial class REEMBOLSO
    {
        public int ID { get; set; }
        public bool ESTADO { get; set; }
        public string DESCRIPCION { get; set; }
        public string ESTADO_REEMBOLSO { get; set; }
        public System.DateTime FECHA { get; set; }
        public string DETALLE { get; set; }
        public long MONTO { get; set; }
        public long TOTAL { get; set; }
        public int PERSONA_NATURALID { get; set; }
    
        public virtual PERSONA_NATURALes PERSONA_NATURAL { get; set; }
    }
}
