//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_UVM_Control_Presupuestario
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOLICITUD()
        {
            this.PERSONA_NATURAL = new HashSet<PERSONA_NATURALes>();
        }
    
        public int ID { get; set; }
        public long NUMERO_SOLICITUD { get; set; }
        public string DETALLE { get; set; }
        public int PERSONA_JURIDICAID { get; set; }
        public int CAPEXID { get; set; }
        public int OPEXID { get; set; }
    
        public virtual PERSONA_JURIDICAs PERSONA_JURIDICA { get; set; }
        public virtual CAPEX CAPEX { get; set; }
        public virtual OPEX OPEX { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERSONA_NATURALes> PERSONA_NATURAL { get; set; }
    }
}
